#!/bin/ksh
#view production backups in xterms
#

DATE=`date |awk '{print $1" "$2" "$3" "$4} ' `
DAY=`date |awk '{print $3}'`
#### #DAY=$((DAY - 1))
#if [ $1 = '-y' ]
#  then
#    DAY=$((DAY - 1))
#fi

if [ "$DAY" -lt 10 ];then
   DAY="0$DAY"
fi
#print "enter the day of the month"
#read DAY

LIST='adr1 adr2 aruc1 bill1 bill2 cst1 cst2 dds1 dds6 disp1 disp2 eq1 eq2 naru2 ndb2 oars1 oars2 xref1 xref2 help1 mon1'
  
for SYS in `echo $LIST`
do
  print $SYS $SYS $SYS $SYS 
  rsh -l oper den-$SYS tail /var/log/backup/ufsbackup."$DAY"v
#  read
done
#xterm -T den-mon1 -geometry 80x5 -e rsh den-ops1 -l oper tail -f /var/log/backup/den-mon1."$DAY" &
#sleep 2
#xterm -T den-help1 -geometry 80x5 -e rsh den-ops1 -l oper tail -f /var/log/backup/den-help1."$DAY" &


