#!/usr/bin/ksh
# THIS CODE (FROM HERE ON REFERED ONLY TO AS CRAP) IS LICENSED UNDER THE
# STRICT AND TYRANICAL BAITSHOP LICENSE.  PERPETUAL RIGHTS AND
# OWNERSHIP ARE CONVEYED TO USER BY AN UNCONDITIONAL BEER CLAUSE
# (U BUY ADAM OR TO A LESSER EXTENT MIKE A BEER AND U BOUGHT THE CODE)
# 
# ALWAYS FEEL FREE TO:
# DISRTIBUTE FREELY
# CHANGE, DELETE AND/OR LAUGH OUT LOUD AT THIS CODE
# CALL IT YOUR OWN (IF YOU CAN STAND THE EMBARASSMENT)
# DON'T CRY ABOUT MISSING COMMENTS. (COMMENTS ARE FOR SISSIES)
# 
# NEVER EVER UNDER ANY CIRCUMSTANCE DO THE FOLLOWING;
# 	ADD USFULL COMMENTS
#   MAKE MONEY FROM THIS CODE
#   INCLUDE IT IN YOUR 1 ON 1 REVIEW (THIS MEANS U WAGNER)
#   BRAG ABOUT IT OVER A SUSHI LUNCH (mcdonald's is ok)
#   AND MOST OF ALL - EXPECT IT TO WORK!

echo "	The ledgondary snapshot locator!!!"
echo 
echo "	First choose a device type"
echo "	**this would be a list to choose from**"
echo 
echo "	That device has snap shots in the following storade builds"
echo "	Choose a build"
echo "	**this would be a list of builds to choose from**"
echo
echo "	Here is a list of available snapshots"
