#!/usr/bin/ksh
# THIS CODE (FROM HERE ON REFERED ONLY TO AS CRAP) IS LICENSED UNDER THE
# STRICT AND TYRANICAL BAITSHOP LICENSE.  PERPETUAL RIGHTS AND
# OWNERSHIP ARE CONVEYED TO USER BY AN UNCONDITIONAL BEER CLAUSE
# (U BUY ADAM OR TO A LESSER EXTENT MIKE A BEER AND U BOUGHT THE CODE)
#
# ALWAYS FEEL FREE TO:
# DISRTIBUTE FREELY
# CHANGE, DELETE AND/OR LAUGH OUT LOUD AT THIS CODE
# CALL IT YOUR OWN (IF YOU CAN STAND THE EMBARASSMENT)
# DON'T CRY ABOUT MISSING COMMENTS. (COMMENTS ARE FOR SISSIES)
#
# NEVER EVER UNDER ANY CIRCUMSTANCE DO THE FOLLOWING;
#   ADD USFULL COMMENTS
#   MAKE MONEY FROM THIS CODE
#   INCLUDE IT IN YOUR 1 ON 1 REVIEW (THIS MEANS U WAGNER)
#   BRAG ABOUT IT OVER A SUSHI LUNCH (mcdonald's is ok)
#   AND MOST OF ALL - EXPECT IT TO WORK!


rv_select()
{
clear
print "\n\n	---->    Revision Menu    <----\n \n \n" ;

    PS3="	
	 What Function do You want to perform? : " 

    select WHAT_FUNCT in "Search for a single patch revision" "Check the config-matrix file" "Quit"
do
   case $WHAT_FUNCT in

      "Search for a single patch revision")
	rv_show_patch ;;

      "Check the config-matrix file")
       	rv_list_patch ;;

      "Quit")
     	exit ;;   #-----------------------------  Try again

      *)  
	print " !! You Didn't enter a correct choice.  Please retry" ;;
   esac
done
}

rv_select


#
#  $.Log.$
#
# Copyright 2005 Sun Microsystems, Inc.
#
