#!/usr/bin/ksh
# THIS CODE (FROM HERE ON REFERED ONLY TO AS CRAP) IS LICENSED UNDER THE
# STRICT AND TYRANICAL BAITSHOP LICENSE.  PERPETUAL RIGHTS AND
# OWNERSHIP ARE CONVEYED TO USER BY AN UNCONDITIONAL BEER CLAUSE
# (U BUY ADAM OR TO A LESSER EXTENT MIKE A BEER AND U BOUGHT THE CODE)
# 
# ALWAYS FEEL FREE TO:
# DISRTIBUTE FREELY
# CHANGE, DELETE AND/OR LAUGH OUT LOUD AT THIS CODE
# CALL IT YOUR OWN (IF YOU CAN STAND THE EMBARASSMENT)
# DON'T CRY ABOUT MISSING COMMENTS. (COMMENTS ARE FOR SISSIES)
# 
# NEVER EVER UNDER ANY CIRCUMSTANCE DO THE FOLLOWING;
# 	ADD USFULL COMMENTS
#   MAKE MONEY FROM THIS CODE
#   INCLUDE IT IN YOUR 1 ON 1 REVIEW (THIS MEANS U WAGNER)
#   BRAG ABOUT IT OVER A SUSHI LUNCH (mcdonald's is ok)
#   AND MOST OF ALL - EXPECT IT TO WORK!


LYNX="/net/zila/export/dsqa/tools/bin/lynx -dump"
SUNSOLVE="http://sunsolve.central/search/advsearch.do?collection=PATCH&collection=PATCHPRTS&type=collections&max=10&queryKey1=" 

clear
print "\tThis utility will retrieve the known patch revisions"
print "\tavailable on Sunsolve for the specified patch\n"
print "\tPlease enter the first 6 numbers of the patch"
read PATCHROOT
print "\n\tSearching.....\n"
$LYNX "$SUNSOLVE"$PATCHROOT | grep Document
print "\n\tPress Return to continue"
read;


#
#  $.Log.$
#
# Copyright 2005 Sun Microsystems, Inc.
#
